version: '3.7'
services:
  backend:
    container_name: backend-crypto-monitor
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  db:
    container_name: database-crypto-monitor
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    tty: true
    volumes:
      - ./deploy/database/database.sql:/docker-entrypoint-initdb.d/data.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  frontend:
    container_name: frontend-crypto-monitor
    build: ./frontend
    ports:
      - "5173:5173"
    restart: always
    environment:
      - VITE_API_URL=${REACT_APP_BACKEND_URL}

  nginx:
    container_name: nginx-crypto-monitor
    image: nginx:latest
    restart: always
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/nginx/access.log:/var/log/nginx/access.log
      - ./deploy/nginx/error.log:/var/log/nginx/error.log
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
      - pgadmin

  pgadmin:
    container_name: pgadmin-crypto-monitor
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data: